services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-pl_reg}
      POSTGRES_USER: ${POSTGRES_USER:-pl_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pl_pass}

    ports:
      - "${DB_PORT:-5432}:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-pl_user}"]
      interval: 5s
      timeout: 3s
      retries: 5

  pgweb:
    image: sosedoff/pgweb:latest
    ports:
      - "9090:8081"
    environment:
      PGWEB_DATABASE_URL: postgres://${POSTGRES_USER:-pl_user}:${POSTGRES_PASSWORD:-pl_pass}@postgres:${DB_PORT:-5432}/${POSTGRES_DB:-pl_reg}?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
